/**
 * Admin API-key oversight routes (see docs/api-keys.md).
 *
 * Every handler is gated on `requireAdmin`. Owners manage their own keys via
 * Better Auth's `/api/auth/api-key/*` endpoints (self-service, session-scoped);
 * these routes exist because the plugin has no cross-user surface, and an
 * admin responding to a compromised key needs fleet-wide list + revoke without
 * waiting for the owner.
 */

import { requireAdmin } from "../auth/middleware";
import { auth } from "../auth/betterAuth";
import {
  badRequest,
  json,
  notFound,
  optionalString,
  parseJsonBody,
} from "../lib/http";
import { recordAuditFromRequest } from "../services/auditLog";
import {
  deleteApiKey,
  listApiKeyById,
  listApiKeys,
  setApiKeyEnabled,
  type ApiKeyAdminView,
} from "../services/apiKeys";

/**
 * Validate an apikey path id. Unlike the panel's own tables, `apikey.id` is
 * generated by Better Auth (nanoid-style), not a UUID, so this is a shape and
 * length sanity check for the parameterized SQL below, not a UUID gate.
 */
function requireKeyId(value: string | undefined): string {
  const id = value?.trim() ?? "";
  if (id.length < 8 || id.length > 128 || !/^[A-Za-z0-9_-]+$/.test(id)) {
    throw badRequest('"keyId" must be a valid API key id');
  }
  return id;
}

/** The key view the list/create endpoints return, plus the owner-session note. */
function keyAuditMetadata(view: ApiKeyAdminView): Record<string, unknown> {
  // The display prefix is already public (stored for exactly this purpose);
  // the full key material never enters the audit trail.
  return {
    keyName: view.name,
    keyPrefix: view.prefix,
    ownerId: view.ownerId || null,
    ownerEmail: view.ownerEmail,
  };
}

/** GET /api/admin/api-keys. Every key on the panel, with owner context. */
export async function handleAdminListApiKeys(request: Request): Promise<Response> {
  await requireAdmin(request);

  const url = new URL(request.url);
  const q = url.searchParams.get("q") ?? undefined;
  const keys = await listApiKeys({ q });
  return json({ keys });
}

/**
 * POST /api/admin/api-keys. Mints a key for the *calling admin*.
 *
 * Creation is delegated to the plugin (`auth.api.createApiKey`) so hashing,
 * prefixing and expiry stay library-owned; the session (cookie or the admin's
 * own key, via the plugin's session synthesis) fixes the owner. An admin
 * cannot mint a key into someone else's account from this route. The full key
 * is returned exactly once and never stored in plaintext.
 */
export async function handleAdminCreateApiKey(request: Request): Promise<Response> {
  const admin = await requireAdmin(request);

  const body = await parseJsonBody(request);
  const name = optionalString(body, "name", { max: 64 }) ?? "Admin key";

  // The plugin resolves the owner from the session carried by these headers.
  const created = (await auth.api.createApiKey({
    headers: request.headers,
    body: { name },
  })) as { id: string; name: string; prefix: string; key: string; start: string | null };

  const view = await listApiKeyById(created.id);

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.create",
    targetType: "api_key",
    targetId: created.id,
    metadata: {
      keyName: created.name,
      keyPrefix: created.prefix,
      ownerId: admin.id,
      ownerEmail: admin.email,
    },
  });

  return json({ key: view, token: created.key }, 201);
}

/**
 * PATCH /api/admin/api-keys/:id. Enables or disables any key.
 *
 * Disabling is the reversible compromise response (the row, its usage counters
 * and prefix survive for forensics); deletion is the destructive one. An
 * expired key reads as expired regardless of `enabled`.
 */
export async function handleAdminSetApiKeyEnabled(
  request: Request,
  keyId: string,
): Promise<Response> {
  const admin = await requireAdmin(request);
  const id = requireKeyId(keyId);

  const body = await parseJsonBody(request);
  if (typeof body.enabled !== "boolean") {
    throw badRequest('"enabled" must be a boolean');
  }

  const view = await setApiKeyEnabled(id, body.enabled);
  if (!view) throw notFound("API key not found");

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.update",
    targetType: "api_key",
    targetId: id,
    metadata: { ...keyAuditMetadata(view), enabled: view.enabled },
  });

  return json({ key: view });
}

/** DELETE /api/admin/api-keys/:id. Revokes any key (hard delete, like the plugin's own). */
export async function handleAdminDeleteApiKey(
  request: Request,
  keyId: string,
): Promise<Response> {
  const admin = await requireAdmin(request);
  const id = requireKeyId(keyId);

  const view = await deleteApiKey(id);
  if (!view) throw notFound("API key not found");

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.delete",
    targetType: "api_key",
    targetId: id,
    metadata: keyAuditMetadata(view),
  });

  return json({ key: view });
}
