/**
 * Admin API-key oversight routes (see docs/api-keys.md).
 *
 * Every handler is gated on `requireAdmin`. Owners manage their own keys via
 * Better Auth's `/api/auth/api-key/*` endpoints (self-service, session-scoped);
 * these routes exist because the plugin has no cross-user surface, and an
 * admin responding to a compromised key needs fleet-wide list + revoke without
 * waiting for the owner.
 */

import {
  describeScopes,
  sanitizeApiKeyScopes,
  type ApiKeyScopes,
} from "@/lib/api-key-scopes";
import { assertScopeSubset, requireAdmin } from "../auth/middleware";
import { auth } from "../auth/betterAuth";
import {
  badRequest,
  json,
  notFound,
  optionalString,
  parseJsonBody,
} from "../lib/http";
import { recordAuditFromRequest } from "../services/auditLog";
import {
  deleteApiKey,
  listApiKeyById,
  listApiKeys,
  setApiKeyEnabled,
  setApiKeyScopes,
  type ApiKeyAdminView,
} from "../services/apiKeys";

/**
 * Validate an apikey path id. Unlike the panel's own tables, `apikey.id` is
 * generated by Better Auth (nanoid-style), not a UUID, so this is a shape and
 * length sanity check for the parameterized SQL below, not a UUID gate.
 */
function requireKeyId(value: string | undefined): string {
  const id = value?.trim() ?? "";
  if (id.length < 8 || id.length > 128 || !/^[A-Za-z0-9_-]+$/.test(id)) {
    throw badRequest('"keyId" must be a valid API key id');
  }
  return id;
}

/** The key view the list/create endpoints return, plus the owner-session note. */
function keyAuditMetadata(view: ApiKeyAdminView): Record<string, unknown> {
  // The display prefix is already public (stored for exactly this purpose);
  // the full key material never enters the audit trail.
  return {
    keyName: view.name,
    keyPrefix: view.prefix,
    ownerId: view.ownerId || null,
    ownerEmail: view.ownerEmail,
    // The grant is the security-relevant half of a key: "an admin key was
    // minted" and "an admin key scoped to backups:read was minted" are very
    // different entries to read back six months later.
    scopes: describeScopes(view.scopes),
  };
}

/**
 * Read an optional `permissions` object off a request body.
 *
 * Three inputs, three meanings, and they must not be conflated: absent means
 * "don't change / unrestricted", explicit `null` means "unrestricted", and an
 * object means a scoped grant. An object that sanitizes to nothing is rejected
 * rather than stored, because a key that can reach nothing is almost certainly
 * a mistake in the caller, not a deliberate grant -- and disabling the key is
 * the way to express "this key should do nothing".
 */
function optionalScopes(
  body: Record<string, unknown>,
  key = "permissions",
): ApiKeyScopes | null | undefined {
  const value = body[key];
  if (value === undefined) return undefined;
  if (value === null) return null;

  if (typeof value !== "object" || Array.isArray(value)) {
    throw badRequest(`"${key}" must be an object of resource → ["read","write"]`);
  }

  const scopes = sanitizeApiKeyScopes(value);
  if (Object.keys(scopes).length === 0) {
    throw badRequest(
      `"${key}" granted no known resource. Omit it for an unrestricted key, or name at least one resource.`,
    );
  }
  return scopes;
}

/** GET /api/admin/api-keys. Every key on the panel, with owner context. */
export async function handleAdminListApiKeys(request: Request): Promise<Response> {
  await requireAdmin(request);

  const url = new URL(request.url);
  const q = url.searchParams.get("q") ?? undefined;
  const keys = await listApiKeys({ q });
  return json({ keys });
}

/**
 * POST /api/admin/api-keys. Mints a key for the *calling admin*.
 *
 * Creation is delegated to the plugin (`auth.api.createApiKey`) so hashing,
 * prefixing and expiry stay library-owned; the session (cookie or the admin's
 * own key, via the plugin's session synthesis) fixes the owner. An admin
 * cannot mint a key into someone else's account from this route. The full key
 * is returned exactly once and never stored in plaintext.
 */
export async function handleAdminCreateApiKey(request: Request): Promise<Response> {
  const admin = await requireAdmin(request);

  const body = await parseJsonBody(request);
  const name = optionalString(body, "name", { max: 64 }) ?? "Admin key";
  const scopes = optionalScopes(body) ?? null;

  // An admin driving this route *through a scoped key* may not mint a broader
  // one. Being an admin is authority over the panel, not permission for a
  // credential to exceed itself, so attenuation applies here exactly as it does
  // on the plugin's own create endpoint.
  await assertScopeSubset(request, scopes);

  // The plugin resolves the owner from the session carried by these headers.
  const created = (await auth.api.createApiKey({
    headers: request.headers,
    body: { name, ...(scopes ? { permissions: scopes } : {}) },
  })) as { id: string; name: string; prefix: string; key: string; start: string | null };

  const view = await listApiKeyById(created.id);

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.create",
    targetType: "api_key",
    targetId: created.id,
    metadata: {
      keyName: created.name,
      keyPrefix: created.prefix,
      ownerId: admin.id,
      ownerEmail: admin.email,
      scopes: describeScopes(scopes),
    },
  });

  return json({ key: view, token: created.key }, 201);
}

/**
 * PATCH /api/admin/api-keys/:id. Enables/disables any key, and re-scopes it.
 *
 * Disabling is the reversible compromise response (the row, its usage counters
 * and prefix survive for forensics); deletion is the destructive one. An
 * expired key reads as expired regardless of `enabled`.
 *
 * Re-scoping is the third, narrower response: a key that turns out to be doing
 * more than it needs can be cut down without being rotated, so the script using
 * it keeps working with less authority instead of breaking. Both fields are
 * optional; sending neither is a no-op the route rejects rather than audits.
 */
export async function handleAdminSetApiKeyEnabled(
  request: Request,
  keyId: string,
): Promise<Response> {
  const admin = await requireAdmin(request);
  const id = requireKeyId(keyId);

  const body = await parseJsonBody(request);
  const enabled = body.enabled;
  if (enabled !== undefined && typeof enabled !== "boolean") {
    throw badRequest('"enabled" must be a boolean');
  }
  const scopes = optionalScopes(body);
  if (enabled === undefined && scopes === undefined) {
    throw badRequest('Send "enabled" and/or "permissions"');
  }

  // Widening a key is a grant, so the caller's own credential has to be able to
  // make it: the same attenuation rule that governs minting.
  if (scopes !== undefined) await assertScopeSubset(request, scopes);

  // Read the grant before changing it so the audit entry carries both sides.
  // Only useful when the scope is actually moving.
  const before = scopes === undefined ? null : await listApiKeyById(id);

  let view: ApiKeyAdminView | null = null;
  if (scopes !== undefined) {
    view = await setApiKeyScopes(id, scopes);
    if (!view) throw notFound("API key not found");
  }
  if (enabled !== undefined) {
    view = await setApiKeyEnabled(id, enabled);
  }
  if (!view) throw notFound("API key not found");

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.update",
    targetType: "api_key",
    targetId: id,
    metadata: {
      ...keyAuditMetadata(view),
      enabled: view.enabled,
      ...(scopes === undefined
        ? {}
        : { scopesBefore: describeScopes(before?.scopes ?? null) }),
    },
  });

  return json({ key: view });
}

/** DELETE /api/admin/api-keys/:id. Revokes any key (hard delete, like the plugin's own). */
export async function handleAdminDeleteApiKey(
  request: Request,
  keyId: string,
): Promise<Response> {
  const admin = await requireAdmin(request);
  const id = requireKeyId(keyId);

  const view = await deleteApiKey(id);
  if (!view) throw notFound("API key not found");

  await recordAuditFromRequest(request, {
    userId: admin.id,
    action: "apikey.delete",
    targetType: "api_key",
    targetId: id,
    metadata: keyAuditMetadata(view),
  });

  return json({ key: view });
}
