/**
 * Database provisioning against the shared per-node MariaDB container.
 *
 * The agent owns the Docker socket, so SQL is executed by `docker exec`-ing
 * the `mariadb` client inside the `citadel-node-db` container — the panel never
 * speaks the MySQL protocol directly. This keeps the DB admin password on the
 * agent (delivered per-request by the panel over the authenticated bearer
 * channel) and avoids a second network path the panel would have to secure.
 *
 * Network attachment is also here: when a server's owner provisions a database,
 * the agent attaches that server's container to `node_db_net` so the game can
 * reach MariaDB. ICC is disabled on the network, so the container can reach the
 * DB but not other tenants.
 */

import type Docker from "dockerode";
import { docker } from "./client";
import {
  attachToNetwork,
  detachFromNetwork,
} from "./container";
import { execInContainer } from "./exec";
import { config } from "../config";
import { badRequest, conflict, notFound, serviceUnavailable } from "../http";

/** The standard MariaDB/MySQL port. */
export const DB_PORT = 3306;

/**
 * The shape of a DB/user identifier the panel may ask us to create.
 *
 * MariaDB identifiers are 64 chars max and must start with a letter or
 * underscore, followed by letters, digits, or underscores. We additionally
 * require a leading `db_`/`u_` prefix and cap at 48 chars — comfortably under
 * the limit, and the panel never generates anything close to that.
 */
const DB_NAME_RE = /^db_[a-z0-9]{1,45}$/i;
const DB_USER_RE = /^u_[a-z0-9]{1,45}$/i;

/**
 * Validate a DB name or user the panel wants to create/drop.
 *
 * These values are interpolated directly into SQL (backticked for identifiers,
 * single-quoted for the user host), so they must be vetted before use. The
 * panel generates them, but the agent is root-equivalent on this MariaDB, so
 * it defends itself: a value that doesn't match the strict identifier shape is
 * rejected with a 400 before any SQL runs.
 */
export function assertValidDbIdentifier(name: string, kind: "name" | "user"): void {
  const re = kind === "name" ? DB_NAME_RE : DB_USER_RE;
  if (!re.test(name)) {
    const what = kind === "name" ? "database name" : "database user";
    throw badRequest(
      `Invalid ${what} "${name.slice(0, 64)}". Must match ${re.source} ` +
        "(generated by the panel; this value is not user-supplied).",
    );
  }
}

export interface NodeDbInfo {
  /** The MariaDB container's IP on `node_db_net`, or null if not attached. */
  host: string | null;
  port: number;
  containerName: string;
  networkName: string;
}

/**
 * Resolve the MariaDB container and its IP on the node DB network.
 *
 * Returns `host: null` when the container does not exist or is not on the
 * network, so the caller can surface a clear "node DB not set up" error rather
 * than a connection failure.
 */
export async function getNodeDbInfo(): Promise<NodeDbInfo> {
  const networkName = config.nodeDbNetwork;
  const containerName = config.nodeDbContainer;

  const matches = await docker.listContainers({
    all: true,
    filters: { name: [containerName] },
  });
  const info = matches.find((c) => (c.Names ?? []).some((n) => n === `/${containerName}`));

  if (!info) {
    return { host: null, port: DB_PORT, containerName, networkName };
  }

  const net = info.NetworkSettings?.Networks?.[networkName];
  return {
    host: net?.IPAddress ?? null,
    port: DB_PORT,
    containerName,
    networkName,
  };
}

/**
 * Throw when the node database is not available, with an actionable message.
 *
 * Called before any SQL operation so a node that has not run `setup-db` fails
 * cleanly instead of producing confusing exec errors. Also checks the network
 * is not misconfigured in a way that would block the game-server → DB path:
 * `node_db_net` must allow inter-container communication, or a server container
 * attached to it can never reach MariaDB (the connection times out).
 */
export async function requireNodeDb(): Promise<{ containerId: string; networkName: string }> {
  const networkName = config.nodeDbNetwork;
  const containerName = config.nodeDbContainer;

  const matches = await docker.listContainers({
    all: true,
    filters: { name: [containerName] },
  });
  const info = matches.find((c) => (c.Names ?? []).some((n) => n === `/${containerName}`));

  if (!info) {
    throw serviceUnavailable(
      `The node database container "${containerName}" was not found. ` +
        `Run "bun run setup-db" on this node to create it.`,
    );
  }

  await assertNetworkAllowsIcc(networkName);

  return { containerId: info.Id, networkName };
}

/**
 * Reject a `node_db_net` that has ICC disabled.
 *
 * Older `setup-db` runs created the network with `enable_icc=false` under the
 * mistaken belief that it isolated tenants while still allowing DB access. It
 * does not: ICC=false drops all inter-container traffic on the bridge, so a
 * server container attached to the network can never reach MariaDB — the TCP
 * connect simply times out. Tenant isolation comes from MariaDB's per-database
 * user grants, not the network.
 *
 * We fail loudly here (rather than letting provisions succeed at the SQL level
 * and then silently fail at the network level) so the operator gets one clear
 * instruction: recreate the network.
 */
async function assertNetworkAllowsIcc(networkName: string): Promise<void> {
  let net: Docker.NetworkInspectInfo | null = null;
  try {
    net = await docker.getNetwork(networkName).inspect();
  } catch {
    // Network missing entirely — the container-message above covers the spirit.
    return;
  }
  const icc = net.Options?.["com.docker.network.bridge.enable_icc"];
  if (icc === "false") {
    throw serviceUnavailable(
      `The "${networkName}" Docker network has inter-container communication ` +
        `disabled (enable_icc=false), which blocks server containers from ` +
        `reaching the database. Recreate it with ICC enabled: ` +
        `"docker network rm ${networkName} && docker network create ` +
        `--driver bridge -o com.docker.network.bridge.enable_icc=true ${networkName}", ` +
        `then re-attach the database container: ` +
        `"docker network connect ${networkName} ${config.nodeDbContainer}". ` +
        `Tenant isolation is enforced by MariaDB user grants, not the network.`,
    );
  }
}

/**
 * Execute SQL against the MariaDB container using the `mariadb` client.
 *
 * The admin password is passed through an env var on the exec (`MYSQL_PWD`)
 * rather than a CLI argument, so it does not appear in the process list. Output
 * is captured from stdout/stderr; a non-zero exit code throws with the stderr
 * tail so a failed provision is visible.
 *
 * The exec is driven by `execInContainer` rather than dockerode's
 * `exec.start({ hijack: true })`: hijack relies on Node's `http` upgrade
 * mechanics, which Bun does not implement (see `docker/exec.ts`).
 */
async function execSql(
  containerId: string,
  adminUser: string,
  adminPassword: string,
  sql: string,
): Promise<string> {
  const { stdout, stderr, exitCode } = await execInContainer(
    docker,
    config.dockerSocket,
    containerId,
    {
      cmd: ["mariadb", "-u", adminUser, "-h", "127.0.0.1", "-e", sql],
      env: [`MYSQL_PWD=${adminPassword}`],
    },
  );

  if (exitCode !== 0) {
    const detail = (stderr || stdout).trim().slice(0, 500);
    throw badRequest(`Database SQL failed (exit ${exitCode}): ${detail}`);
  }
  return stdout;
}

/** A database the agent has provisioned (or confirmed to exist). */
export interface ProvisionedDatabase {
  name: string;
  user: string;
  /** The host address server containers should connect to. */
  host: string;
  port: number;
}

/**
 * Create a database and a scoped user on the node's MariaDB, then attach the
 * server's container to `node_db_net` so it can reach the DB.
 *
 * The grants are scoped strictly to the one database — the new user has no
 * access to anything else on the shared instance. The password is generated by
 * the panel (which stores it encrypted) and passed through; the agent never
 * persists it.
 *
 * `dbName` and `dbUser` are generated by the panel (server-id prefix + random
 * suffix) so each database on a server gets a distinct name — the agent does
 * not derive them. The agent validates them before interpolating into SQL.
 */
export async function provisionServerDatabase(
  serverId: string,
  dbName: string,
  dbUser: string,
  adminUser: string,
  adminPassword: string,
  dbPassword: string,
): Promise<ProvisionedDatabase> {
  assertValidDbIdentifier(dbName, "name");
  assertValidDbIdentifier(dbUser, "user");

  const { containerId, networkName } = await requireNodeDb();

  // CREATE DATABASE IF NOT EXISTS keeps this idempotent for a retry; the user
  // is created the same way. The GRANT is re-issued each time so a partial
  // failure (DB created, user not) is self-healing.
  const sql = [
    `CREATE DATABASE IF NOT EXISTS \`${dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`,
    // DROP and recreate the user so a re-provision with a new password works.
    `DROP USER IF EXISTS '${dbUser}'@'%';`,
    `CREATE USER '${dbUser}'@'%' IDENTIFIED BY '${dbPassword.replace(/'/g, "''")}';`,
    `GRANT ALL PRIVILEGES ON \`${dbName}\`.* TO '${dbUser}'@'%';`,
    `FLUSH PRIVILEGES;`,
  ].join(" ");

  await execSql(containerId, adminUser, adminPassword, sql);

  // Attach the server's container to the DB network so the game can reach
  // MariaDB. Idempotent: an already-attached container is a no-op.
  const serverContainerName = `citadel-${serverId.slice(0, 12)}`;
  const serverContainerId = await findContainerIdByName(serverContainerName);
  if (serverContainerId) {
    await attachToNetwork(docker, networkName, serverContainerId);
  }

  const info = await getNodeDbInfo();
  const host = info.host;
  if (!host) {
    throw serviceUnavailable(
      "The node database container has no IP on the DB network. Check that it is running.",
    );
  }

  return { name: dbName, user: dbUser, host, port: DB_PORT };
}

/**
 * Drop a server's database and user, and detach its container from `node_db_net`.
 *
 * Idempotent: a missing database or user is not an error (the DROP IF EXISTS
 * forms handle it), so a retry after a partial failure cleans up fully.
 *
 * `dbName` and `dbUser` are the values the panel stored at creation time — the
 * agent validates and uses them directly rather than re-deriving from serverId.
 */
export async function dropServerDatabase(
  serverId: string,
  dbName: string,
  dbUser: string,
  adminUser: string,
  adminPassword: string,
): Promise<void> {
  assertValidDbIdentifier(dbName, "name");
  assertValidDbIdentifier(dbUser, "user");

  const { containerId, networkName } = await requireNodeDb();

  const sql = [
    `DROP DATABASE IF EXISTS \`${dbName}\`;`,
    `DROP USER IF EXISTS '${dbUser}'@'%';`,
    `FLUSH PRIVILEGES;`,
  ].join(" ");

  await execSql(containerId, adminUser, adminPassword, sql);

  // Detach the server's container from the DB network. Best-effort: a container
  // that is already gone or not attached is a no-op.
  const serverContainerName = `citadel-${serverId.slice(0, 12)}`;
  const serverContainerId = await findContainerIdByName(serverContainerName);
  if (serverContainerId) {
    try {
      await detachFromNetwork(docker, networkName, serverContainerId);
    } catch {
      // Not attached, or container removed — nothing to do.
    }
  }
}

/** Resolve a container id by exact name, or null if it does not exist. */
async function findContainerIdByName(name: string): Promise<string | null> {
  const matches = await docker.listContainers({
    all: true,
    filters: { name: [name] },
  });
  const exact = matches.find((c) => (c.Names ?? []).some((n) => n === `/${name}`));
  return exact?.Id ?? null;
}

// --- Database explorer queries --------------------------------------------------
//
// The panel's database explorer runs its SQL as the *scoped* per-database user,
// not the admin. The user's grants cover exactly one database, so MariaDB itself
// contains the blast radius of anything the panel composes — the admin
// credential is never in play for explorer traffic.

/**
 * One statement's result: column names (empty when the statement returned no
 * rows — the mariadb XML format only names fields on rows) and the rows as
 * nullable strings. Values stay strings end-to-end: BIGINT ids must not round-
 * trip through JavaScript numbers, and MariaDB coerces string literals against
 * numeric columns on INSERT/UPDATE anyway.
 */
export interface DbQueryResult {
  columns: string[];
  rows: (string | null)[][];
}

/** Decode the small set of entities the mariadb client emits in `--xml` output. */
function xmlUnescape(value: string): string {
  return value
    .replace(/&#x([0-9a-fA-F]+);/g, (_m, hex: string) =>
      String.fromCodePoint(Number.parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_m, dec: string) => String.fromCodePoint(Number(dec)))
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

const RESULTSET_RE = /<resultset\b[^>]*>([\s\S]*?)<\/resultset>/g;
const ROW_RE = /<row>([\s\S]*?)<\/row>/g;
const FIELD_RE = /<field\b([^>]*?)(?:\/>|>([\s\S]*?)<\/field>)/g;

/**
 * Parse the mariadb client's `--xml` output into {@link DbQueryResult}s.
 *
 * Why XML and not the default tab-separated `--batch` mode: batch mode escapes
 * tabs/newlines but renders NULL and the literal string "NULL" identically, so
 * an owner's data could be silently mis-read (and a row edit keyed on a
 * mis-read value would target the wrong row). The XML format carries
 * `xsi:nil="true"` for real NULLs, which removes the ambiguity, and the client
 * XML-escapes values so `</field>` can never appear inside one.
 *
 * The format is rigid (a resultset per statement, a row per record, a field per
 * cell), so regex extraction is deterministic here — this is not general XML
 * parsing. Statements that return no result set (DDL, INSERT, …) emit nothing
 * and simply do not appear in the output.
 */
export function parseMysqlXmlOutput(stdout: string): DbQueryResult[] {
  const results: DbQueryResult[] = [];
  for (const resultset of stdout.matchAll(RESULTSET_RE)) {
    const body = resultset[1] ?? "";
    let columns: string[] = [];
    const rows: (string | null)[][] = [];

    for (const row of body.matchAll(ROW_RE)) {
      const values: (string | null)[] = [];
      for (const field of (row[1] ?? "").matchAll(FIELD_RE)) {
        const attrs = field[1] ?? "";
        const nameMatch = /\bname\s*=\s*"([^"]*)"/.exec(attrs);
        const isNil = /\bxsi:nil\s*=\s*"(?:true|1)"/.test(attrs);
        const text = field[2];
        values.push(isNil || text === undefined ? null : xmlUnescape(text));
        if (columns.length < values.length) {
          columns.push(xmlUnescape(nameMatch?.[1] ?? ""));
        }
      }
      rows.push(values);
    }

    results.push({ columns, rows });
  }
  return results;
}

/** Upper bound on SQL the agent will exec for one explorer request. */
const MAX_EXPLORER_SQL = 128 * 1024;

/**
 * Run SQL against one server database **as its scoped user**.
 *
 * The credentials arrive in the request body (the panel decrypts the user's
 * stored password); the agent never persists them. The database is preselected
 * via the CLI argument, so `DATABASE()` in information_schema filters resolves
 * to the one database the user can see. Output is captured as `--xml` and
 * parsed by {@link parseMysqlXmlOutput}.
 *
 * The SQL text itself is composed by the panel from structured explorer
 * operations — the browser never sends SQL. The panel holds root-equivalent
 * trust on this channel already (it delivers the admin credential for
 * provisioning), so trusting it to compose statements changes nothing; running
 * them as the scoped user is what keeps a bug or XSS from reaching anything
 * beyond the one database.
 */
export async function runServerDatabaseSql(
  dbName: string,
  dbUser: string,
  dbPassword: string,
  sqlText: string,
): Promise<DbQueryResult[]> {
  assertValidDbIdentifier(dbName, "name");
  assertValidDbIdentifier(dbUser, "user");
  if (sqlText.length === 0 || sqlText.length > MAX_EXPLORER_SQL) {
    throw badRequest(
      `"sql" must be between 1 and ${MAX_EXPLORER_SQL} characters.`,
    );
  }

  const { containerId } = await requireNodeDb();

  const { stdout, stderr, exitCode } = await execInContainer(
    docker,
    config.dockerSocket,
    containerId,
    {
      cmd: [
        "mariadb",
        "-u",
        dbUser,
        "-h",
        "127.0.0.1",
        "--default-character-set=utf8mb4",
        "--xml",
        "-e",
        sqlText,
        dbName,
      ],
      env: [`MYSQL_PWD=${dbPassword}`],
    },
  );

  if (exitCode !== 0) {
    const detail = (stderr || stdout).trim().slice(0, 500);
    throw badRequest(`Database query failed (exit ${exitCode}): ${detail}`);
  }
  return parseMysqlXmlOutput(stdout);
}
