/**
 * Lifecycle of this node's shared MariaDB container.
 *
 * `database.ts` is the *use* of the node database (create a per-server database,
 * run explorer SQL). This module is its *existence*: create the network, the
 * data volume and the container, start it, stop it, report its state. The panel
 * drives all four from the node's admin page, which is why this exists at all:
 * the agent already holds the Docker socket, so a node database is one API call
 * away, and asking an operator to SSH in and run a script was the only reason
 * it ever looked like a manual step.
 *
 * It also creates the account the panel uses (`citadel_<hex>`, generated by the
 * panel), so an operator never types or copies a database credential.
 *
 * `scripts/setup-node-db.ts` is a thin CLI over the same functions, so the
 * button and the script cannot drift apart.
 *
 * Two properties are deliberate and load-bearing:
 *
 * 1. **No published host ports.** MariaDB is reachable only from containers on
 *    `node_db_net`, never from the host's network or the internet. Nothing here
 *    may add a `PortBindings` entry.
 * 2. **ICC enabled on `node_db_net`.** Tenant isolation comes from MariaDB's
 *    per-database user grants (see `provisionServerDatabase`), not from the
 *    bridge. With ICC off, no game server could reach the database at all; see
 *    {@link ensureNodeDbNetwork} for the bug that taught us this.
 */

import type Docker from "dockerode";
import { randomBytes } from "node:crypto";
import { docker } from "./client";
import {
  ensureImage,
  ensureNetwork,
  removeContainer,
  removeNetwork,
} from "./container";
import { execInContainer } from "./exec";
import { config } from "../config";
import { badRequest, conflict, notFound } from "../http";

/** The standard MariaDB/MySQL port. Not published on the host. */
export const NODE_DB_PORT = 3306;

/** MariaDB's data directory inside the container; the volume's mount point. */
const DATA_DIR = "/var/lib/mysql";

/**
 * How long to wait for MariaDB to answer a ping.
 *
 * First boot runs the whole initialisation (system tables, root user), which is
 * comfortably the slowest case at 10-30s on a busy node. A restart of an
 * initialised volume is a few seconds. The panel's HTTP timeout for setup is
 * wider than this on purpose, so the timeout the operator hits is this one, with
 * its own message, rather than a bare fetch abort.
 */
const READY_TIMEOUT_MS = 120_000;

/**
 * Consecutive access-denied pings tolerated before giving up on a credential.
 *
 * At one probe every two seconds this is a ~6s grace for the tail end of a first
 * boot, after which "wrong credential" is the honest answer rather than two more
 * minutes of pretending to start.
 */
const DENIED_TOLERANCE = 3;

/** Docker returns 404 for "no such container/volume". */
function isNotFound(error: unknown): boolean {
  return (error as { statusCode?: number } | null)?.statusCode === 404;
}

/**
 * Generate a MariaDB password.
 *
 * Alphanumeric only: the value goes to the `mariadb` client through `MYSQL_PWD`
 * and, for the panel's own account, into one `CREATE USER … IDENTIFIED BY`
 * literal. Keeping it free of quote, backslash and shell characters removes a
 * whole class of quoting surprise from every call site rather than relying on
 * escaping being right everywhere. 32 chars of this alphabet is ~190 bits.
 *
 * Normally the *panel* generates it (it stores the secret encrypted either way,
 * so it owns it) and passes it in. This is here for the CLI script, which has no
 * panel behind it, and for the container's throwaway root password.
 */
export function generateRootPassword(length = 32): string {
  const alphabet =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const bytes = randomBytes(length);
  let out = "";
  for (let i = 0; i < length; i += 1) {
    out += alphabet[bytes[i]! % alphabet.length];
  }
  return out;
}

/**
 * The credential the panel holds for this node's database.
 *
 * `user` is `root` for nodes set up before the panel minted its own account, and
 * a generated `citadel_<hex>` for everything since. Both are root-equivalent on
 * this MariaDB (creating per-server databases and granting privileges to their
 * users requires it), so the named account is not a privilege reduction: it is a
 * credential the panel owns end to end, separate from the image's root account,
 * and one that shows up as itself in `SHOW PROCESSLIST` and the audit trail.
 */
/**
 * How much to throw away before creating the container again.
 *
 * - `"container"`: the container only. The volume, its databases and its
 *   accounts survive, so this needs the credential that volume already knows.
 *   For a container that is broken, misconfigured or gone.
 * - `"all"`: container **and** volume. The only thing that resets a credential
 *   nobody holds, and it destroys every database on the node. The panel gates it
 *   behind a typed confirmation.
 */
export type NodeDbRecreate = "container" | "all";

export interface NodeDbAdmin {
  user: string;
  password: string;
}

/**
 * A MariaDB account name the panel may ask us to create.
 *
 * Interpolated into `CREATE USER`/`GRANT`, so it is vetted before use. The panel
 * generates it, but this agent is root-equivalent on this database, so it
 * defends itself. `root` is accepted (the pre-existing arrangement) and means
 * "no extra account", handled by the caller.
 */
const ADMIN_USER_RE = /^[a-z][a-z0-9_]{2,31}$/i;

/** Passwords are generated alphanumeric; anything else is a caller bug. */
const ADMIN_PASSWORD_RE = /^[A-Za-z0-9]{16,128}$/;

/** Validate the credential before any of it reaches SQL or a container env. */
function assertValidAdmin(admin: NodeDbAdmin): void {
  if (!ADMIN_USER_RE.test(admin.user)) {
    throw badRequest(
      `Invalid database admin user "${admin.user.slice(0, 64)}". Must match ` +
        `${ADMIN_USER_RE.source} (generated by the panel).`,
    );
  }
  if (!ADMIN_PASSWORD_RE.test(admin.password)) {
    throw badRequest(
      '"adminPassword" must be 16-128 alphanumeric characters (generated by the panel).',
    );
  }
}

/**
 * The bridge `node_db_net` is created with.
 *
 * ICC **on**, for the reason in the module header. Outbound NAT stays on to
 * match the posture of every other managed network (MariaDB does not need it,
 * but a network that behaves differently from its siblings is a trap).
 */
export function nodeDbNetworkConfig(networkName: string): Docker.NetworkCreateOptions {
  return {
    Name: networkName,
    Driver: "bridge",
    CheckDuplicate: true,
    Internal: false,
    Options: {
      "com.docker.network.bridge.enable_icc": "true",
      "com.docker.network.bridge.enable_ip_masquerade": "true",
    },
    Labels: { "citadel.managed": "true", "citadel.role": "node-db" },
  } as Docker.NetworkCreateOptions;
}

/**
 * The container spec for the node database.
 *
 * Pure, so the two properties that matter can be unit-tested without a daemon:
 * no host port bindings, and the data directory on a named volume.
 *
 * The volume is why the container is disposable. Without it MariaDB's data would
 * live in the container's writable layer, and every `docker rm` (an image bump,
 * a botched setup, a manual cleanup) would silently destroy every tenant's
 * database. With it, removing and recreating the container is a restart.
 *
 * `RestartPolicy: unless-stopped` is the opposite of the game containers' `no`
 * (see `hardening.ts`). Their state machine lives in the panel and a container
 * that came back on its own would fight it. The node database has no such
 * state: it should be up whenever the node is, and an admin who stopped it from
 * the panel wants it to stay stopped across a reboot, which is exactly what
 * `unless-stopped` means.
 */
export function nodeDbContainerConfig(spec: {
  containerName: string;
  image: string;
  networkName: string;
  volumeName: string;
  rootPassword: string;
}): Docker.ContainerCreateOptions {
  return {
    name: spec.containerName,
    Image: spec.image,
    // The one env var MariaDB requires to initialise. The image creates
    // root@'%' with GRANT ALL ON *.*, which is what per-server provisioning
    // needs later.
    Env: [`MARIADB_ROOT_PASSWORD=${spec.rootPassword}`],
    Labels: { "citadel.managed": "true", "citadel.role": "node-db" },
    HostConfig: {
      // Attach to node_db_net only: not the default bridge, and no host ports.
      NetworkMode: spec.networkName,
      Binds: [`${spec.volumeName}:${DATA_DIR}`],
      RestartPolicy: { Name: "unless-stopped" },
      PublishAllPorts: false,
      LogConfig: {
        Type: "json-file",
        Config: { "max-size": "10m", "max-file": "3" },
      },
    },
  };
}

/**
 * Create `node_db_net`, repairing a legacy one that cannot work.
 *
 * Early versions of the setup script created this bridge with
 * `enable_icc=false`, on the mistaken belief that it isolated tenants while
 * still allowing database access. It does not: ICC=false drops all
 * inter-container traffic on the bridge, so a game server attached to it can
 * never reach MariaDB and the TCP connect just times out. Isolation comes from
 * MariaDB's per-database grants (see `provisionServerDatabase`), never from
 * here.
 *
 * A network is only metadata, so when nothing is attached we recreate it rather
 * than handing the operator a shell command: the whole point of the setup button
 * is that a node with a legacy network ends up working, not informed. With
 * containers still attached, recreating would silently detach them, so that case
 * is refused with the instructions instead.
 */
export async function ensureNodeDbNetwork(): Promise<void> {
  const networkName = config.nodeDbNetwork;

  let existing: Docker.NetworkInspectInfo | null = null;
  try {
    existing = await docker.getNetwork(networkName).inspect();
  } catch (error) {
    if (!isNotFound(error)) throw error;
  }

  if (existing?.Options?.["com.docker.network.bridge.enable_icc"] === "false") {
    const attached = Object.keys(existing.Containers ?? {}).length;
    if (attached > 0) {
      throw conflict(iccDisabledMessage(networkName, attached));
    }
    await removeNetwork(docker, networkName);
  }

  await ensureNetwork(docker, networkName, nodeDbNetworkConfig(networkName));
}

/**
 * Reject a `node_db_net` that has ICC disabled, at use time.
 *
 * {@link ensureNodeDbNetwork} repairs this during setup; this is the guard on
 * every later operation, for a network an operator recreated by hand. Shared
 * with `database.ts` so the diagnosis is written once.
 */
export async function assertNodeDbNetworkAllowsIcc(networkName: string): Promise<void> {
  let net: Docker.NetworkInspectInfo | null = null;
  try {
    net = await docker.getNetwork(networkName).inspect();
  } catch {
    // Network missing entirely; the caller's "no container" message covers it.
    return;
  }
  if (net.Options?.["com.docker.network.bridge.enable_icc"] === "false") {
    throw conflict(
      iccDisabledMessage(networkName, Object.keys(net.Containers ?? {}).length),
    );
  }
}

/** The one explanation of an ICC-disabled node DB network, and the way out. */
function iccDisabledMessage(networkName: string, attached: number): string {
  return (
    `The "${networkName}" Docker network has inter-container communication ` +
    `disabled (enable_icc=false), which blocks server containers from reaching ` +
    `the database, and ${attached} container${attached === 1 ? " is" : "s are"} ` +
    `still attached to it. Stop those containers, then recreate the network: ` +
    `"docker network rm ${networkName} && docker network create --driver bridge ` +
    `-o com.docker.network.bridge.enable_icc=true ${networkName}". Tenant ` +
    `isolation is enforced by MariaDB user grants, not the network.`
  );
}

/**
 * Find the node DB container, whatever its state.
 *
 * Shared with `database.ts` so "which container is the node database" is
 * decided once. Name filters are substring matches in Docker, hence the exact
 * `/name` comparison.
 */
export async function findNodeDbContainer(): Promise<Docker.ContainerInfo | null> {
  const containerName = config.nodeDbContainer;
  const matches = await docker.listContainers({
    all: true,
    filters: { name: [containerName] },
  });
  return (
    matches.find((c) => (c.Names ?? []).some((n) => n === `/${containerName}`)) ??
    null
  );
}

/** The three things a ping can tell us. See {@link probePing}. */
export type NodeDbProbe = "alive" | "unreachable" | "denied";

/** What the panel shows on the node's database card. */
export interface NodeDbStatus {
  /** False when the container does not exist: the "Set up" case. */
  exists: boolean;
  /** Docker's status string ("running", "exited", …), or null when absent. */
  state: string | null;
  /** True once MariaDB answers a ping, so "running" means "usable". */
  ready: boolean;
  /**
   * Why `ready` is false, when a credential was supplied to check with.
   *
   * `"denied"` is the one an operator has to act on: the database is up and
   * refusing the panel's account, which no amount of waiting fixes. Null when no
   * credential was supplied (nothing was probed).
   */
  probe: NodeDbProbe | null;
  /** The container's IP on `node_db_net`; null when absent or detached. */
  host: string | null;
  port: number;
  containerName: string;
  networkName: string;
  volumeName: string;
  /** The image the container actually runs, or the configured default. */
  image: string;
}

/**
 * Report the container's state and address.
 *
 * `ready` is only probed when the container is running and a credential was
 * supplied, because a ping costs an exec (~50ms) and the answer is meaningless
 * for a stopped container. The panel passes the credential it stored, so the
 * status card can distinguish "running" from "running and accepting
 * connections", which is the difference between a working node and one whose
 * first boot is still initialising. It also means "ready" proves the panel's own
 * account works, not merely that some database is listening.
 */
export async function getNodeDbStatus(admin?: NodeDbAdmin): Promise<NodeDbStatus> {
  const info = await findNodeDbContainer();
  const base = {
    containerName: config.nodeDbContainer,
    networkName: config.nodeDbNetwork,
    volumeName: config.nodeDbVolume,
    port: NODE_DB_PORT,
  };

  if (!info) {
    return {
      ...base,
      exists: false,
      state: null,
      ready: false,
      probe: null,
      host: null,
      image: config.nodeDbImage,
    };
  }

  const running = info.State === "running";
  const probe = running && admin ? await probePing(info.Id, admin) : null;

  return {
    ...base,
    exists: true,
    state: info.State ?? null,
    ready: probe === "alive",
    probe,
    // Docker reports an empty string, not a missing field, for a stopped
    // container's IP. `|| null` collapses both into "no address".
    host: info.NetworkSettings?.Networks?.[base.networkName]?.IPAddress || null,
    image: info.Image ?? config.nodeDbImage,
  };
}

/**
 * Create the network, volume and container, wait until MariaDB answers, and make
 * sure the panel's own account exists.
 *
 * Idempotent by design, because the operation it wraps is slow enough to time
 * out on a first-boot image pull: a retry with the *same* credential finds the
 * existing container, verifies the credential against it, and returns the same
 * answer. That matters because the panel stores the credential before calling
 * here (it generated it), so a retry that recreated the container with a fresh
 * one would strand every database on the old one.
 *
 * A container that exists but rejects the credential is a 409, not a silent
 * recreate. It means either a previous panel install owns this node's database or
 * the operator ran the script by hand; both are recoverable by hand, and neither
 * is worth destroying data over.
 */
export async function setUpNodeDb(
  admin: NodeDbAdmin,
  options: { recreate?: NodeDbRecreate } = {},
): Promise<NodeDbStatus> {
  assertValidAdmin(admin);

  const containerName = config.nodeDbContainer;
  const volumeName = config.nodeDbVolume;

  await ensureNodeDbNetwork();

  const existing = await findNodeDbContainer();

  // "Delete and start over": the only thing that truly resets a database whose
  // credential nobody has, because the accounts live in the volume. Destroys
  // every database inside it, which is why the panel makes the operator confirm
  // it and never picks it automatically.
  if (options.recreate === "all") {
    if (existing) await removeContainer(docker, existing.Id);
    await removeVolume(volumeName);
  } else if (options.recreate === "container" && existing) {
    // "Recreate the container": for a container that is broken or gone while the
    // volume (and therefore the data and the accounts) is intact. The credential
    // must be the one that volume already knows; a fresh one would be refused,
    // which `waitUntilReady` now says immediately instead of waiting out a
    // two-minute timeout.
    await removeContainer(docker, existing.Id);
  }

  const current = options.recreate ? await findNodeDbContainer() : existing;

  if (current) {
    // Start it before probing: a stopped container cannot answer, and "setup"
    // on an existing-but-stopped database should leave it usable.
    if (current.State !== "running") {
      await docker.getContainer(current.Id).start();
    }
    await waitUntilReady(current.Id, admin);
    return getNodeDbStatus(admin);
  }

  // Read this BEFORE creating the volume, or the answer is always "not fresh":
  // `ensureVolume` is what makes it exist. Getting that order wrong made a
  // first-ever setup skip creating the panel's account and then time out waiting
  // for a credential nothing had been told about.
  //
  // Whether MariaDB is initialising from scratch decides whether the root
  // password passed below has any effect at all: the image applies
  // MARIADB_ROOT_PASSWORD only to an empty data directory. On a kept volume the
  // accounts already exist, so none is created and the credential probe is what
  // proves the setup.
  const freshData = await volumeIsEmpty(volumeName);
  const isRoot = admin.user.toLowerCase() === "root";

  await ensureVolume(volumeName);
  await ensureImage(docker, config.nodeDbImage);

  // When the panel asked for its own named account, the image's root password is
  // generated here and then deliberately forgotten: nothing needs it again,
  // because the account created below has the same privileges, and a second
  // root-equivalent secret that no one holds is one fewer thing to leak.
  const rootPassword = isRoot ? admin.password : generateRootPassword(32);

  const container = await docker.createContainer(
    nodeDbContainerConfig({
      containerName,
      image: config.nodeDbImage,
      networkName: config.nodeDbNetwork,
      volumeName,
      rootPassword,
    }),
  );
  await container.start();

  if (!freshData) {
    // Existing data: the accounts are already in the volume. Prove the panel's
    // own credential directly, and fail fast (not in two minutes) if this volume
    // belongs to a different install.
    await waitUntilReady(container.id, admin);
    return getNodeDbStatus(admin);
  }

  await waitUntilReady(container.id, { user: "root", password: rootPassword });

  if (!isRoot) {
    await createAdminAccount(container.id, rootPassword, admin);
    // Prove the account the panel will actually use, not the one we booted with.
    await waitUntilReady(container.id, admin);
  }

  return getNodeDbStatus(admin);
}

/**
 * Remove the data volume, and with it every database on this node.
 *
 * Only reached through an explicit `recreate: "all"`, which the panel only sends
 * after the operator confirms a dialog naming how many databases it holds.
 */
async function removeVolume(name: string): Promise<void> {
  try {
    await docker.getVolume(name).remove({ force: true });
  } catch (error) {
    if (!isNotFound(error)) throw error;
  }
}

/**
 * Whether a data volume has never been initialised by MariaDB.
 *
 * Docker does not report a volume's contents on a plain inspect, so this uses
 * the one fact it does give reliably: a volume that does not exist yet is empty.
 * Anything else is assumed to hold data, which is the safe direction: MariaDB
 * skips its initialisation on a populated directory anyway, so the only cost of
 * being wrong is that the panel proves its credential (which it must do in
 * either case) instead of creating an account.
 */
async function volumeIsEmpty(name: string): Promise<boolean> {
  try {
    await docker.getVolume(name).inspect();
    return false;
  } catch (error) {
    if (isNotFound(error)) return true;
    throw error;
  }
}

/**
 * Create the panel's admin account inside a freshly initialised MariaDB.
 *
 * `ALTER USER` follows `CREATE USER IF NOT EXISTS` so a re-run converges on the
 * password the panel holds instead of failing on an account that already exists
 * with a different one.
 *
 * The grant is `ALL PRIVILEGES ON *.* … WITH GRANT OPTION` because that is what
 * the panel's job needs: it creates a database and a user per server and grants
 * that user rights on that database (see `provisionServerDatabase`). Narrowing it
 * would break provisioning rather than contain anything, since the account has
 * to be able to create accounts.
 *
 * Host `'%'`, not `'localhost'`: every caller reaches MariaDB from another
 * container on `node_db_net`, so from MariaDB's point of view no connection ever
 * comes from localhost.
 *
 * Both values are validated by {@link assertValidAdmin} before they get here,
 * and the password is alphanumeric, so neither literal can carry a quote.
 */
async function createAdminAccount(
  containerId: string,
  rootPassword: string,
  admin: NodeDbAdmin,
): Promise<void> {
  const sql = [
    `CREATE USER IF NOT EXISTS '${admin.user}'@'%' IDENTIFIED BY '${admin.password}';`,
    `ALTER USER '${admin.user}'@'%' IDENTIFIED BY '${admin.password}';`,
    `GRANT ALL PRIVILEGES ON *.* TO '${admin.user}'@'%' WITH GRANT OPTION;`,
    "FLUSH PRIVILEGES;",
  ].join(" ");

  const { stdout, stderr, exitCode } = await execInContainer(
    docker,
    config.dockerSocket,
    containerId,
    {
      cmd: ["mariadb", "-u", "root", "-h", "127.0.0.1", "-e", sql],
      env: [`MYSQL_PWD=${rootPassword}`],
    },
  );

  if (exitCode !== 0) {
    const detail = (stderr || stdout).trim().slice(0, 500);
    throw conflict(
      `The node database started but its admin account could not be created ` +
        `(exit ${exitCode}): ${detail}`,
    );
  }
}

/**
 * Start the node database and wait until it accepts connections.
 *
 * "Started" is reported only once MariaDB answers a ping, so the admin who
 * clicked Start does not get a green badge over a database that is still
 * replaying its redo log. Already running is success, not a conflict.
 */
export async function startNodeDb(admin?: NodeDbAdmin): Promise<NodeDbStatus> {
  const info = await requireNodeDbContainer();

  if (info.State !== "running") {
    try {
      await docker.getContainer(info.Id).start();
    } catch (error) {
      // 304 = already started, which a concurrent request can produce.
      if ((error as { statusCode?: number }).statusCode !== 304) throw error;
    }
  }

  if (admin) await waitUntilReady(info.Id, admin);
  return getNodeDbStatus(admin);
}

/**
 * Stop the node database.
 *
 * 30s of grace, because mysqld's shutdown flushes to disk and a SIGKILL there
 * is how you get a crash recovery on the next boot. Already stopped is success.
 *
 * Nothing is detached from `node_db_net`: the server containers stay attached
 * and simply fail to connect while this is down, which is what makes Start a
 * complete undo.
 */
export async function stopNodeDb(): Promise<NodeDbStatus> {
  const info = await requireNodeDbContainer();

  if (info.State === "running") {
    try {
      await docker.getContainer(info.Id).stop({ t: 30 });
    } catch (error) {
      // 304 = already stopped.
      if ((error as { statusCode?: number }).statusCode !== 304) throw error;
    }
  }

  return getNodeDbStatus();
}

/** The container, or a 404 naming the setup action that creates it. */
async function requireNodeDbContainer(): Promise<Docker.ContainerInfo> {
  const info = await findNodeDbContainer();
  if (!info) {
    throw notFound(
      `The node database container "${config.nodeDbContainer}" does not exist ` +
        `on this node. Set it up first.`,
    );
  }
  return info;
}

/** Create the data volume if it is not already there. */
async function ensureVolume(name: string): Promise<void> {
  try {
    await docker.getVolume(name).inspect();
    return;
  } catch (error) {
    if (!isNotFound(error)) throw error;
  }
  await docker.createVolume({
    Name: name,
    Labels: { "citadel.managed": "true", "citadel.role": "node-db" },
  });
}

/**
 * What `mariadb-admin ping` said, as the given account.
 *
 * Three outcomes, and the difference between the last two is the whole point:
 * "not up yet" is worth waiting out, "wrong credential" never becomes right. A
 * loop that treats them the same spends two minutes reporting progress on
 * something that failed on the first attempt.
 *
 * Classified by the output text, not the exit code, because `mariadb-admin`
 * exits **0** on an access-denied ping (verified against mariadb:11) and 1 when
 * the server is unreachable. Matching on the status line is the only thing that
 * distinguishes them.
 *
 * The image ships `mariadb-admin`, not the `mysqladmin` symlink: the wrong name
 * fails with "executable file not found" on every probe, which reads exactly
 * like a database that never came up. The password goes through `MYSQL_PWD`
 * rather than `-p`, so it stays out of the container's process list.
 */
async function probePing(
  containerId: string,
  admin: NodeDbAdmin,
): Promise<NodeDbProbe> {
  let output: string;
  try {
    const { stdout, stderr } = await execInContainer(
      docker,
      config.dockerSocket,
      containerId,
      {
        cmd: ["mariadb-admin", "ping", "-h", "127.0.0.1", "-u", admin.user],
        env: [`MYSQL_PWD=${admin.password}`],
      },
    );
    output = `${stdout}${stderr}`;
  } catch {
    // Exec itself failed: the container is still booting, or is gone.
    return "unreachable";
  }

  if (output.includes("mysqld is alive")) return "alive";
  if (/access denied/i.test(output)) return "denied";
  return "unreachable";
}

/**
 * Poll until MariaDB answers, or throw.
 *
 * The container reports "running" long before mysqld listens, so every caller
 * that promises a usable database has to wait here.
 *
 * An access-denied answer short-circuits the wait. It is not a stage of
 * starting up: the credential is wrong and will still be wrong in two minutes.
 * A few denials are tolerated first (`DENIED_TOLERANCE`) because the very end of
 * a first boot can briefly answer before its grants are flushed, and a false
 * "wrong credential" on a working setup would be worse than six extra seconds.
 */
async function waitUntilReady(
  containerId: string,
  admin: NodeDbAdmin,
  options: { onTimeout?: () => Error; onDenied?: () => Error } = {},
): Promise<void> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  let denials = 0;

  while (Date.now() < deadline) {
    const probe = await probePing(containerId, admin);
    if (probe === "alive") return;

    if (probe === "denied") {
      denials += 1;
      if (denials >= DENIED_TOLERANCE) {
        throw options.onDenied?.() ?? credentialRejected(admin.user);
      }
    } else {
      denials = 0;
    }

    await new Promise((resolve) => setTimeout(resolve, 2_000));
  }

  throw (
    options.onTimeout?.() ??
    conflict(
      `The node database did not accept connections within ` +
        `${Math.round(READY_TIMEOUT_MS / 1000)}s. Check the container's logs ` +
        `("docker logs ${config.nodeDbContainer}").`,
    )
  );
}

/**
 * The error for "this database exists and does not know this account".
 *
 * The advice matters as much as the diagnosis, and the obvious advice is wrong:
 * recreating the container does **not** reset the password. MariaDB only applies
 * `MARIADB_ROOT_PASSWORD` when it initialises an empty data directory, so on an
 * existing volume the old credentials survive every `docker rm` (verified
 * against mariadb:11). Only the credential the volume already knows, or deleting
 * the volume with the databases in it, changes this.
 */
function credentialRejected(user: string): Error {
  return conflict(
    `The database on this node refused the account "${user}": it exists and ` +
      `does not know this credential. Recreating the container will not help, ` +
      `because MariaDB keeps its accounts in the data volume ` +
      `("${config.nodeDbVolume}"), not in the container. Either register this ` +
      `node with the credentials that database already knows, or delete the ` +
      `volume and start a new database, which destroys every database inside it.`,
  );
}
