import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath } from "node:url";

const DEFAULTS = {
  POSTGRES_USER: "citadel",
  POSTGRES_DB: "citadel",
  FRONTEND_URL: "http://localhost:3000",
  FIRST_USER_BECOMES_ADMIN: "true",
  NODE_API_TIMEOUT_MS: "15000",
  WATCHER_INTERVAL_SECONDS: "60",
  SUSPICION_FLAG_THRESHOLD: "60",
  SUSPICION_AUTO_SUSPEND: "false",
  SUSPICION_AUTO_SUSPEND_THRESHOLD: "115",
} as const;

const ENV_FILE = process.env.ENV_FILE
  ? resolve(process.cwd(), process.env.ENV_FILE)
  : resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", ".env");

const args = new Set(process.argv.slice(2));
const nonInteractive = args.has("--yes") || args.has("-y") || !input.isTTY || !output.isTTY;

function generatedSecret(bytes: number): string {
  return randomBytes(bytes).toString("base64url");
}

function isBlank(value: string | undefined): boolean {
  return value === undefined || value.trim().length === 0;
}

function stripQuotes(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function parseEnv(text: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator < 1) continue;
    const key = line.slice(0, separator).trim();
    const value = stripQuotes(line.slice(separator + 1).trim());
    values.set(key, value);
  }
  return values;
}

function setEnvValue(text: string, key: string, value: string): string {
  const lines = text.length > 0 ? text.split("\n") : [];
  const replacement = `${key}=${value}`;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]!;
    const separator = line.indexOf("=");
    if (separator < 1) continue;
    const lineKey = line.slice(0, separator).trim();
    if (lineKey !== key) continue;
    lines[index] = replacement;
    return lines.join("\n");
  }

  if (lines.length > 0 && lines[lines.length - 1]!.trim() !== "") lines.push("");
  lines.push(replacement);
  return lines.join("\n");
}

function ensureTrailingNewline(text: string): string {
  return text.endsWith("\n") ? text : `${text}\n`;
}

function composeDatabaseUrl(values: Map<string, string>): string {
  const user = values.get("POSTGRES_USER") ?? DEFAULTS.POSTGRES_USER;
  const password = values.get("POSTGRES_PASSWORD") ?? "citadel";
  const database = values.get("POSTGRES_DB") ?? DEFAULTS.POSTGRES_DB;
  return `postgres://${encodeURIComponent(user)}:${encodeURIComponent(password)}@localhost:5432/${encodeURIComponent(database)}`;
}

function initialTemplate(): string {
  return [
    "# CitadelPanel local configuration",
    "# Generated by `bun run setup`. Existing values are preserved unless you edit them.",
    "",
    "# Local setup/migrations connect here.",
    "DATABASE_URL=",
    "",
    "# Docker Compose postgres service defaults.",
    `POSTGRES_USER=${DEFAULTS.POSTGRES_USER}`,
    "POSTGRES_PASSWORD=",
    `POSTGRES_DB=${DEFAULTS.POSTGRES_DB}`,
    "",
    "# Next.js control plane secrets.",
    "PANEL_ENCRYPTION_KEY=",
    "BETTER_AUTH_SECRET=",
    `FRONTEND_URL=${DEFAULTS.FRONTEND_URL}`,
    `FIRST_USER_BECOMES_ADMIN=${DEFAULTS.FIRST_USER_BECOMES_ADMIN}`,
    "",
    "# Bun node backend token.",
    "AGENT_TOKEN=",
    "",
    "# Optional tuning.",
    `NODE_API_TIMEOUT_MS=${DEFAULTS.NODE_API_TIMEOUT_MS}`,
    `WATCHER_INTERVAL_SECONDS=${DEFAULTS.WATCHER_INTERVAL_SECONDS}`,
    `SUSPICION_FLAG_THRESHOLD=${DEFAULTS.SUSPICION_FLAG_THRESHOLD}`,
    `SUSPICION_AUTO_SUSPEND=${DEFAULTS.SUSPICION_AUTO_SUSPEND}`,
    `SUSPICION_AUTO_SUSPEND_THRESHOLD=${DEFAULTS.SUSPICION_AUTO_SUSPEND_THRESHOLD}`,
    "",
  ].join("\n");
}

async function ask(question: string, fallback: string): Promise<string> {
  if (nonInteractive) return fallback;

  const rl = createInterface({ input, output });
  try {
    const answer = await rl.question(`${question} [${fallback}]: `);
    return answer.trim() || fallback;
  } finally {
    rl.close();
  }
}

async function ensurePrompted(
  current: Map<string, string>,
  planned: Map<string, string>,
  key: string,
  fallback: string,
  label: string,
  promptAlways = false,
): Promise<void> {
  const existing = current.get(key);
  if (!promptAlways && !isBlank(existing)) return;

  const value = await ask(label, isBlank(existing) ? fallback : existing!);
  if (value === existing) return;
  current.set(key, value);
  planned.set(key, value);
}

async function ensureGenerated(
  current: Map<string, string>,
  planned: Map<string, string>,
  key: string,
  bytes: number,
  label: string,
): Promise<void> {
  if (!isBlank(current.get(key))) return;
  const generated = generatedSecret(bytes);
  const value = await ask(label, generated);
  current.set(key, value);
  planned.set(key, value);
}

async function main(): Promise<void> {
  await mkdir(dirname(ENV_FILE), { recursive: true });

  const existed = existsSync(ENV_FILE);
  let text = existed ? await readFile(ENV_FILE, "utf8") : initialTemplate();
  const current = parseEnv(text);
  const planned = new Map<string, string>();

  if (!nonInteractive) {
    console.log(`\nCitadelPanel environment setup`);
    console.log(`Writing ${ENV_FILE}`);
    if (!existed) {
      console.log("No .env file found — creating one now.\n");
    } else {
      console.log("Missing values will be prompted for; existing values are kept.\n");
    }
  }

  await ensurePrompted(
    current,
    planned,
    "POSTGRES_USER",
    DEFAULTS.POSTGRES_USER,
    "Postgres user",
    true,
  );
  await ensurePrompted(
    current,
    planned,
    "POSTGRES_PASSWORD",
    current.get("POSTGRES_PASSWORD") ?? generatedSecret(24),
    "Postgres password",
    true,
  );
  await ensurePrompted(
    current,
    planned,
    "POSTGRES_DB",
    DEFAULTS.POSTGRES_DB,
    "Postgres database name",
    true,
  );
  await ensurePrompted(
    current,
    planned,
    "DATABASE_URL",
    composeDatabaseUrl(current),
    "Database URL used by local setup/dev",
    true,
  );
  await ensurePrompted(
    current,
    planned,
    "FRONTEND_URL",
    DEFAULTS.FRONTEND_URL,
    "Public panel URL",
    true,
  );
  await ensureGenerated(current, planned, "PANEL_ENCRYPTION_KEY", 48, "Panel encryption key");
  await ensureGenerated(current, planned, "BETTER_AUTH_SECRET", 48, "Better Auth secret");
  await ensurePrompted(
    current,
    planned,
    "FIRST_USER_BECOMES_ADMIN",
    DEFAULTS.FIRST_USER_BECOMES_ADMIN,
    "First registered user becomes admin (true/false)",
    true,
  );
  await ensureGenerated(current, planned, "AGENT_TOKEN", 48, "Node backend token");
  await ensurePrompted(
    current,
    planned,
    "NODE_API_TIMEOUT_MS",
    DEFAULTS.NODE_API_TIMEOUT_MS,
    "Node API timeout in ms",
  );
  await ensurePrompted(
    current,
    planned,
    "WATCHER_INTERVAL_SECONDS",
    DEFAULTS.WATCHER_INTERVAL_SECONDS,
    "Watcher interval in seconds",
  );
  await ensurePrompted(
    current,
    planned,
    "SUSPICION_FLAG_THRESHOLD",
    DEFAULTS.SUSPICION_FLAG_THRESHOLD,
    "Suspicion flag threshold",
  );
  await ensurePrompted(
    current,
    planned,
    "SUSPICION_AUTO_SUSPEND",
    DEFAULTS.SUSPICION_AUTO_SUSPEND,
    "Auto-suspend suspicious servers (true/false)",
  );
  await ensurePrompted(
    current,
    planned,
    "SUSPICION_AUTO_SUSPEND_THRESHOLD",
    DEFAULTS.SUSPICION_AUTO_SUSPEND_THRESHOLD,
    "Auto-suspend threshold",
  );

  for (const [key, value] of planned) {
    text = setEnvValue(text, key, value);
  }

  await writeFile(ENV_FILE, ensureTrailingNewline(text), "utf8");

  if (planned.size === 0) {
    console.log(`[env] ${ENV_FILE} already had all required values`);
    return;
  }

  console.log(`[env] updated ${ENV_FILE}`);
  for (const key of planned.keys()) {
    console.log(`  - set ${key}`);
  }
}

await main();
